CREATE TABLE IF NOT EXISTS shifts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL,
  period INTEGER NOT NULL,
  memo TEXT NOT NULL DEFAULT '',
  UNIQUE(date, period),
  CHECK(period BETWEEN 1 AND 4)
);
